Tackling issue #71
UtrechtUniversity/workshop-introduction-to-python pull request #74
Opened 2023-08-24 13:33 UTC by chStaiger

2023-09-07 09:31 UTC, RoelBrouwer requested changes
Generally good, a few small changes required before merge

2023-09-07 09:31 UTC, RoelBrouwer commented on book/data-science-with-pandas-2.ipynb
> +    "In contrast to the first example where we just retrieved the series of numbers of the column, the double brackets `[[...]]` tell Pandas to format the values of the two columns as a Pandas DataFr
- What first example? On the second read, I think I get what you mean. However, it is confusing that you contrast the 'first example' with the use of double brackets later, because the first example also uses double brackets.
- Maybe "series of values" instead of "series of numbers", or even just "values in the column".

2023-09-07 09:31 UTC, RoelBrouwer commented on book/data-science-with-pandas-2.ipynb
> +    "You see that you get for each key a bar. We can get a more insightful plot when we `unstack` the values for each key and only het the plot numbers as x-axis:"
```suggestion
    "For each key, there is a bar in the plot. We can get a more insightful plot when we `unstack` the values for each key and only put the numbers on the x-axis:"
```

2023-09-07 09:31 UTC, RoelBrouwer commented on book/data-science-with-pandas-2.ipynb
- Please clean the output (and execution counts etc.)
- Heading 'Interactive part': remove our change to something that reflects the content of the section

2023-09-07 12:35 UTC, chStaiger commented on book/data-science-with-pandas-2.ipynb
Done!

2023-09-07 12:35 UTC, chStaiger commented on book/data-science-with-pandas-2.ipynb
> +    "In contrast to the first example where we just retrieved the series of numbers of the column, the double brackets `[[...]]` tell Pandas to format the values of the two columns as a Pandas DataFr
Rephrased!

2023-09-07 12:40 UTC, chStaiger commented on book/data-science-with-pandas-2.ipynb
> +    "You see that you get for each key a bar. We can get a more insightful plot when we `unstack` the values for each key and only het the plot numbers as x-axis:"
Thanks, it is in the document now. Ready for merge!

2023-09-07 14:00 UTC, RoelBrouwer commented on book/data-science-with-pandas-2.ipynb
I believe 'Interactive part' is still in there as a heading

2023-09-07 15:21 UTC, chStaiger commented on book/data-science-with-pandas-2.ipynb
You are right. Changed it!

2023-09-08 09:25 UTC, RoelBrouwer approved these changes

2023-09-27 15:51 UTC, merged